const data = {
    "total_quantity_per_item": {
            "Pile of stickers": 3769,
            "OpenAI credits": 497,
            "YubiKey": 447,
            "Domain for 1 year": 405,
            "Sticker of your choice": 396,
            "Raspberry Pi Zero 2W Kit": 350,
            "Pinecil": 171,
            "E-fidgets Made by Micha!": 143,
            "Wacom Intuos S": 131,
            "iPad 10th Gen + 1st Gen Apple Pencil": 120,
            "Notebook from GitHub": 105,
            "Soldering iron + solder": 97,
            "Helping hands": 94,
            "Multimeter": 90,
            "PineTime by PINE64": 85,
            "Anthropic credits": 83,
            "Logic Analyzer": 79,
            "Flipper Zero": 78,
            "Tuxedo pick set + clear training lock": 76,
            "Keychron K6 Pro": 73,
            "Leatherman Skeletool": 62,
            "USB-C Charger (30W)": 61,
            "One by Wacom": 61,
            "Digital Ocean credits": 60,
            "Good Sci-Fi Book": 55,
            "Bambu Lab A1 mini": 53,
            "Breadboard + jumper wires": 46,
            "2 Arcade Posters 11x17 inches. Designed by Acon & Krishna. Good for bedroom walls.": 39,
            "Hot glue gun": 33,
            "Samsung T7 1TB SSD (1,050MB/s, beige)": 29,
            "Octocat Plushie": 25,
            "Logitech MX Anywhere 2S (Mouse)": 23,
            "Wacom One display": 20,
            "Quest 3": 18,
            "Heroku credits": 17,
            "GitHub Keycaps x8": 16,
            "AirPods Pro": 14,
            "Ryobi 4 Tool Combo Kit": 12,
            "Ryobi Rotary Tool Kit": 12,
            "ThinkPad T490 (14-inch model)": 11,
            "Prusa MINI+": 11,
            "Framework factory seconds": 10,
            "Logitech MX Mechanical": 9,
            "Invertocat Backpack MIIR": 9,
            "Nvidia Tesla P40 GPU (24GB GDDR5)": 5,
            "Arcade Ticket Counter (Timer)": 4,
            "MacBook Air M2": 4,
            "Framework 13 inch": 3,
            "Framework 16 inch": 1 },
    "orders_per_country": {
            "United States": 2609,
            "India": 749,
            "Canada": 638,
            "United Kingdom": 372,
            "Australia": 327,
            "Germany": 238,
            "Italy": 167,
            "Poland": 156,
            "Czech Republic": 104,
            "Singapore": 96,
            "France": 93,
            "New Zealand": 90,
            "Spain": 85,
            "Romania": 71,
            "Hungary": 62,
            "Pakistan": 60,
            "Hong Kong": 60,
            "Thailand": 52,
            "Philippines": 51,
            "United Arab Emirates": 41,
            "Austria": 40,
            "Sri Lanka": 40,
            "Turkey": 40,
            "Netherlands": 35,
            "Sweden": 34,
            "Brazil": 33,
            "Greece": 31,
            "Taiwan": 29,
            "Slovakia": 27,
            "Malaysia": 26,
            "Argentina": 26,
            "Israel": 24,
            "Switzerland": 23,
            "Egypt": 19,
            "China": 19,
            "Belgium": 18,
            "Bangladesh": 17,
            "Ireland": 17,
            "South Korea": 16,
            "Denmark": 15,
            "Kazakhstan": 12,
            "Portugal": 12,
            "Japan": 10,
            "Vietnam": 9,
            "Mexico": 9,
            "Latvia": 8,
            "Saudi Arabia": 8,
            "Slovenia": 5,
            "Estonia": 4,
            "South Africa": 4,
            "Kenya": 3,
            "Chile": 3,
            "Colombia": 3,
            "Uzbekistan": 3,
            "Cyprus": 2,
            "Azerbaijan": 1,
            "Zimbabwe": 1,
            "Costa Rica": 1,
            "Norway": 1,
            "Puerto Rico": 1,
            "Finland": 1,
            "Guatemala": 1,
            "Hrvatska": 1,
            "Jordan": 1,
            "Kuwait": 1,
            },
    "product_images": {
        "2 Arcade Posters 11x17 inches. Designed by Acon & Krishna. Good for bedroom walls.": "https://cloud-ijdgy1kv8-hack-club-bot.vercel.app/0group_1.png",
        "AirPods Pro": "https://cloud-837rvecwy-hack-club-bot.vercel.app/0111851_sp880-airpods-pro-2nd-gen.png",
        "Anthropic credits": "https://cloud-4qxzmw5wz-hack-club-bot.vercel.app/2screenshot_2024-08-26_at_1.14.03___pm.png",
        "Arcade Ticket Counter (Timer)": "https://example.com/ticket-counter.png",
        "Bambu Lab A1 mini": "https://cloud-n8ijhwk64-hack-club-bot.vercel.app/0a1_mini.png",
        "Breadboard + jumper wires": "https://cloud-ogt9k4r4u-hack-club-bot.vercel.app/0breadboard.png",
        "Digital Ocean credits": "https://cloud-itv94wqoe-hack-club-bot.vercel.app/1screenshot_2024-08-26_at_1.23.29___pm.png",
        "Domain for 1 year": "https://cloud-5ttcbislu-hack-club-bot.vercel.app/2screenshot_2024-06-16_at_19.34.55.png",
        "E-fidgets Made by Micha!": "https://cloud-r1yu83g5v-hack-club-bot.vercel.app/0image.png",
        "Flipper Zero": "https://cloud-p2gdpsmd3-hack-club-bot.vercel.app/0top.png",
        "Framework 13 inch": "https://cloud-g0bjmr0sz-hack-club-bot.vercel.app/013in.png",
        "Framework 16 inch": "https://cloud-cqnd9gu78-hack-club-bot.vercel.app/0framework.png",
        "Framework factory seconds": "https://cloud-elfpck7gj-hack-club-bot.vercel.app/1screenshot_2024-06-14_at_07.39.22.png",
        "GitHub Keycaps x8": "https://cloud-q3hnx73my-hack-club-bot.vercel.app/01542509_z_copy.png",
        "Good Sci-Fi Book": "https://cloud-lr8bs9gzg-hack-club-bot.vercel.app/0books.png",
        "Helping hands": "https://cloud-nhghqjofw-hack-club-bot.vercel.app/0image.png",
        "Heroku credits": "https://cloud-itv94wqoe-hack-club-bot.vercel.app/0thumb_2x-f69b79d27f3b816b1237af12e41413e765149da0972f7bdbb1a416329308d962.png",
        "Hot glue gun": "https://cloud-4qxzmw5wz-hack-club-bot.vercel.app/0glue.png",
        "Invertocat Backpack MIIR": "https://cloud-2wpezbt6a-hack-club-bot.vercel.app/1miir.png",
        "Keychron EU/UK K6 Pro": "https://cloud-ephagrx6o-hack-club-bot.vercel.app/1keeb.png",
        "Keychron K6 Pro": "https://cloud-ephagrx6o-hack-club-bot.vercel.app/1keeb.png",
        "Leatherman Skeletool": "https://cloud-dcmjamx8y-hack-club-bot.vercel.app/0image.png",
        "Logic Analyzer": "https://cloud-re8ou8f0i-hack-club-bot.vercel.app/0image.png",
        "Logitech MX Anywhere 2S (Mouse)": "https://cloud-77ecxp5zt-hack-club-bot.vercel.app/0image.png",
        "Logitech MX Mechanical": "https://cloud-gt96uxjmh-hack-club-bot.vercel.app/061__ok6aqtl._ac_uf894_1000_ql80_.png",
        "MacBook Air M2": "https://cloud-9zwbzfbtw-hack-club-bot.vercel.app/00image_from_ios-removebg-preview.png",
        "Multimeter": "https://cloud-fyxfbdwdl-hack-club-bot.vercel.app/0multimeter.png",
        "Notebook from GitHub": "https://cloud-2wpezbt6a-hack-club-bot.vercel.app/0notebook.png",
        "Nvidia Tesla P40 GPU (24GB GDDR5)": "https://cloud-7lhnywkqd-hack-club-bot.vercel.app/0nvidia-tesla-p40_b1ac5a43-34ac-4cd4-8450-3ad7e27321ae_2000x.png",
        "Octocat Plushie": "https://cloud-n716uf1pe-hack-club-bot.vercel.app/0gh_0008_z_dd7b_copy.png",
        "One by Wacom": "https://cloud-eiuq0wqao-hack-club-bot.vercel.app/0onebywacom.png",
        "OpenAI credits": "https://cloud-nozsvexvx-hack-club-bot.vercel.app/0universal_paperclips_title_screen.png",
        "Pile of stickers": "https://cloud-c1gqq7ttf-hack-club-bot.vercel.app/0sticker_pile_2.png",
        "PineTime by PINE64": "https://cloud-4qxzmw5wz-hack-club-bot.vercel.app/1pinetime.png",
        "Pinecil": "https://cloud-3lhacr9fo-hack-club-bot.vercel.app/061ix8eet_dl._ac_sx679_.png",
        "Prusa MINI+": "https://cloud-cqnd9gu78-hack-club-bot.vercel.app/1prusa.png",
        "Quest 3": "https://cloud-7x2qyu0b9-hack-club-bot.vercel.app/0screenshot_2024-06-14_at_08.46.20.png",
        "Raspberry Pi Zero 2W Kit": "https://cloud-5di8nhlvy-hack-club-bot.vercel.app/0image.png",
        "Ryobi 4 Tool Combo Kit": "https://cloud-bbmi9jn0r-hack-club-bot.vercel.app/10image.png",
        "Ryobi Rotary Tool Kit": "https://cloud-bbmi9jn0r-hack-club-bot.vercel.app/00image__1_.png",
        "Samsung T7 1TB SSD (1,050MB/s, beige)": "https://cloud-pnx1i6khl-hack-club-bot.vercel.app/051_7tbplikl._ac_sl1500_.png",
        "Soldering iron + solder": "https://cloud-amz50nt0a-hack-club-bot.vercel.app/0soldering_iron.png",
        "Sticker of your choice": "https://cloud-50x4zfjwx-hack-club-bot.vercel.app/0enjoy_1.png",
        "ThinkPad T490 (14-inch model)": "https://cloud-bscuvqen5-hack-club-bot.vercel.app/045ee3bbe-1519-481a-908e-781f1323a72e-4_f7e8a61e-ae12-4b8d-9c20-68c38709be13.png",
        "Tuxedo pick set + clear training lock": "https://cloud-8ikvjz9g0-hack-club-bot.vercel.app/0image.png",
        "USB-C Charger (30W)": "https://cloud-lit9nkas9-hack-club-bot.vercel.app/051t9lfjeuml._ac_sl1500_.png",
        "Wacom Intuos S": "https://cloud-bi9lc9poq-hack-club-bot.vercel.app/0intuos.png",
        "Wacom One display": "https://cloud-c6nos84m4-hack-club-bot.vercel.app/061zj7gvrvsl._ac_sx679_.png",
        "YubiKey": "https://cloud-elfpck7gj-hack-club-bot.vercel.app/0screenshot_2024-06-14_at_07.42.35.png",
        "iPad 10th Gen + 1st Gen Apple Pencil": "https://cloud-k0uz9sh1c-hack-club-bot.vercel.app/2ipad.png"
    },
    "country_flags": {
            "United States": "https://img.icons8.com/color/96/usa.png",
            "India": "https://img.icons8.com/color/96/india.png",
            "Canada": "https://img.icons8.com/color/96/canada.png",
            "United Kingdom": "https://img.icons8.com/color/96/great-britain.png",
            "Australia": "https://cloud-cxecypp94-hack-club-bot.vercel.app/0icons8-australia-96.png",
            "Germany": "https://img.icons8.com/color/96/germany.png",
            "Italy": "https://img.icons8.com/color/96/italy.png",
            "Poland": "https://img.icons8.com/color/96/poland.png",
            "Czech Republic": "https://img.icons8.com/color/96/czech-republic.png",
            "Singapore": "https://img.icons8.com/color/96/singapore.png",
            "France": "https://img.icons8.com/color/96/france.png",
            "New Zealand": "https://img.icons8.com/color/96/new-zealand.png",
            "Spain": "https://img.icons8.com/color/96/spain.png",
            "Romania": "https://img.icons8.com/color/96/romania.png",
            "Hungary": "https://img.icons8.com/color/96/hungary.png",
            "Pakistan": "https://img.icons8.com/color/96/pakistan.png",
            "Hong Kong": "https://cloud-61w2o7zv0-hack-club-bot.vercel.app/0download.png",
            "Thailand": "https://img.icons8.com/color/96/thailand.png",
            "Philippines": "https://img.icons8.com/color/96/philippines.png",
            "United Arab Emirates": "https://img.icons8.com/color/96/united-arab-emirates.png",
            "Austria": "https://img.icons8.com/color/96/austria.png",
            "Sri Lanka": "https://img.icons8.com/color/96/sri-lanka.png",
            "Turkey": "https://img.icons8.com/color/96/turkey.png",
            "Netherlands": "https://img.icons8.com/color/96/netherlands.png",
            "Sweden": "https://img.icons8.com/color/96/sweden.png",
            "Brazil": "https://img.icons8.com/color/96/brazil.png",
            "Greece": "https://img.icons8.com/color/96/greece.png",
            "Taiwan": "https://img.icons8.com/color/96/taiwan.png",
            "Slovakia": "https://img.icons8.com/color/96/slovakia.png",
            "Malaysia": "https://img.icons8.com/color/96/malaysia.png",
            "Argentina": "https://img.icons8.com/color/96/argentina.png",
            "Israel": "https://img.icons8.com/color/96/israel.png",
            "Switzerland": "https://img.icons8.com/color/96/switzerland.png",
            "Egypt": "https://img.icons8.com/color/96/egypt.png",
            "China": "https://img.icons8.com/color/96/china.png",
            "Belgium": "https://img.icons8.com/color/96/belgium.png",
            "Bangladesh": "https://img.icons8.com/color/96/bangladesh.png",
            "Ireland": "https://img.icons8.com/color/96/ireland.png",
            "South Korea": "https://img.icons8.com/color/96/south-korea.png",
            "Denmark": "https://img.icons8.com/color/96/denmark.png",
            "Kazakhstan": "https://img.icons8.com/color/96/kazakhstan.png",
            "Portugal": "https://img.icons8.com/color/96/portugal.png",
            "Japan": "https://img.icons8.com/color/96/japan.png",
            "Mexico": "https://img.icons8.com/color/96/mexico.png",
            "Latvia": "https://img.icons8.com/color/96/latvia.png",
            "Saudi Arabia": "https://img.icons8.com/color/96/saudi-arabia.png",
            "Estonia": "https://img.icons8.com/color/96/estonia.png",
            "South Africa": "https://img.icons8.com/color/96/south-africa.png",
            "Nigeria": "https://img.icons8.com/color/96/nigeria.png",
            "Kenya": "https://img.icons8.com/color/96/kenya.png",
            "Chile": "https://img.icons8.com/color/96/chile.png",
            "Colombia": "https://img.icons8.com/color/96/colombia.png",
            "Uzbekistan": "https://img.icons8.com/color/96/uzbekistan.png",
            "Slovenia": "https://img.icons8.com/color/96/slovenia.png",
            "Cyprus": "https://img.icons8.com/color/96/cyprus.png",
            "Azerbaijan": "https://img.icons8.com/color/96/azerbaijan.png",
            "Finland": "https://img.icons8.com/color/96/finland.png",
            "Norway": "https://img.icons8.com/color/96/norway.png",
            "Puerto Rico": "https://img.icons8.com/color/96/puerto-rico.png",
            "Russia": "https://img.icons8.com/color/96/russia.png",
            "Guatemala": "https://img.icons8.com/color/96/guatemala.png",
            "Jordan": "https://img.icons8.com/color/96/jordan.png",
            "Vietnam": "https://img.icons8.com/color/96/vietnam.png",
            "Zimbabwe": "https://img.icons8.com/color/96/zimbabwe.png",
            "Costa Rica": "https://img.icons8.com/color/96/costa-rica.png",
            "Hrvatska": "https://img.icons8.com/color/96/croatia.png",
            "Kuwait": "https://img.icons8.com/color/96/kuwait.png",
            "India (india)": "https://img.icons8.com/color/96/india.png"
                    }
};

const itemsGrid = document.getElementById('items-grid');
Object.entries(data.total_quantity_per_item)
    .sort((a, b) => b[1] - a[1]) 
    .forEach(([item, quantity]) => {
        const itemCard = document.createElement('div');
        itemCard.className = 'stat-card';

        const imgSrc = data.product_images[item] || 'default-image-url';
        itemCard.innerHTML = `
            <img src="${imgSrc}" alt="${item}" class="stat-image">
            <h3 class="stat-title">${item}</h3>
            <p class="stat-quantity">Quantity: ${quantity}</p>
        `;

        itemsGrid.appendChild(itemCard);
    });

const countriesGrid = document.getElementById('countries-grid');
Object.entries(data.orders_per_country)
    .sort((a, b) => b[1] - a[1]) 
    .forEach(([country, orders]) => {
        const countryCard = document.createElement('div');
        countryCard.className = 'stat-card';

        const flagSrc = data.country_flags[country] || 'default-flag-url';
        countryCard.innerHTML = `
            <img src="${flagSrc}" alt="${country} flag" class="stat-image">
            <h3 class="stat-title">${country}</h3>
            <p class="stat-quantity">Orders: ${orders}</p>
        `;

        countriesGrid.appendChild(countryCard);
    });
